# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"skip": "00_core.ipynb",
         "ts_lists": "00_core.ipynb",
         "ToElapsed": "00_core.ipynb",
         "make_interval": "00_core.ipynb",
         "melted_ts_2_lists": "00_core.ipynb",
         "m4_base": "01_data.external.ipynb",
         "URLs.m4_daily": "01_data.external.ipynb",
         "pad_zeros": "03_data.load.ipynb",
         "TimeSeriesDataset": "03_data.load.ipynb",
         "encodes": "04_data.transforms.ipynb",
         "decodes": "04_data.transforms.ipynb",
         "ConcreteDropout": "05_models.wavenet.ipynb",
         "WaveNet": "05_models.wavenet.ipynb"}

modules = ["core.py",
           "data/external.py",
           "data/load.py",
           "data/transforms.py",
           "models/wavenet.py"]

doc_url = "https://takotab.github.io/fastseq/"

git_url = "https://github.com/takotab/fastseq/tree/master/"

def custom_doc_links(name): return None
