# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb",
         "m4_base": "01_dataset.ipynb",
         "URLs.m4_daily": "01_dataset.ipynb"}

modules = ["core.py",
           "dataset.py"]

git_url = "https://github.com/takotab/fastseq/tree/master/"


def custom_doc_links(name): return None
