# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['ts_lists', 'melted_ts_2_lists']

# Cell
from fastcore.all import *
import pandas as pd

# Cell
def ts_lists(ts:np.ndarray)-> L:
    """From a `ndarray` of shape (timeseries, max_time) to a list of timeseries with shape (1,time).

    max_time = the lenght of the longest timeserie
    time = the lenght of the non-nan values of that specific timeserie
    """
    lst = L()
    for time_series in ts:
        lst.append(time_series[~np.isnan(time_series)][None,:])
    return lst

# Cell
def melted_ts_2_lists(ts:pd.DataFrame, split_on:str)->L:
    return ts