#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['hello']

#Cell
def hello():
    print("torch.cuda.is_available():", torch.cuda.is_available())
    return "hello"