# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_interpret.ipynb (unless otherwise specified).

__all__ = []

# Cell
from .all import *
from .data.external import *
from fastai2.basics import *
from .models.nbeats import *

# Cell
@typedispatch
def plot_top_losses(x:TSTensorSeq, y:TSTensorSeqy, *args, **kwargs):
    print(x.shape,y.shape, args)
    a = [(_x,TSTensorSeqy(_y, x_len = x.shape[-1], m = 'g'), TSTensorSeqy(pred,x_len = x.shape[-1], m = 'r'))
                for _x, _y, pred in zip(x, y, args[2])]
    show_graphs(a, titles=[str(o.data) for o in args[3]])
