# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_learner.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastcore.all import *
from fastai2.basics import *
from torch.nn import Conv2d, Sequential, Module