# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_data.procs.ipynb (unless otherwise specified).

__all__ = ['CatProc']

# Cell
class CatProc():
    def __init__(self, path, vocab = None, o2i = None):
        if vocab is None and o2i is None:
            vocab, o2i = make_vocab(path)
        self.meta = get_meta(path)
        self.f = CatMultiTfm(vocab = vocab, o2i = o2i)

    def setup(self, files:List[Path]):
        r = []
        for f in files:
            r.append(self._setup(f))
        return r

    def _setup(self, f:Path):
        ts = get_ts_datapoint(f)
        tsm = json2TSMulti(ts, 0, self.meta['col_names']['ts_con_names'][0], ts['_length']-1, 1, self.meta)
        tsm = self.f(tsm)
        for i, cat in enumerate(ts['ts_cat']):
            test_eq(len(tsm[2][i]), len(ts['ts_cat'][cat]))
            ts['ts_cat'][cat] = [o.item() for o in tsm[2][i]]
#         print(tsm)
        for i, cat in enumerate(ts['cat']):
            ts['cat'][cat] = tsm[3][i].item()
        open(f,'wb').write(orjson.dumps(dict(ts)))
        return f
