# AUTOGENERATED! DO NOT EDIT! File to edit: dev/04_data.transforms.ipynb (unless otherwise specified).

__all__ = ['encodes', 'decodes']

# Cell
from fastai2.torch_basics import *
from fastai2.data.all import *

# Cell
@ToTensor
def encodes(self,o):
    return tensor(o)
@ToTensor
def decodes(self,o):
    return np.array(o)