# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/tab.model.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastcore.imports import *
from fastai2.basics import *
from fastai2.data.transforms import *
from fastai2.tabular.core import *
from fastcore.all import *
from ..data.core import *
from ..core import *
